### ISSUE TITLE
Wrong canvas size upon initial render

### ISSUE THREAD

**Issue by mitikov** [Azure-Samples/AzureMapsCodeSamples#104]
Folks, initial map render leads to canvas wrong size (white stripe):

![image](https://user-images.githubusercontent.com/14172414/224758078-8b4de8d4-fce0-421e-8b6e-d99e3d45beb8.png)

If I resize the window it gets corrected straight away (no white stripe, full window size).
Is that something known?

Could you please suggest where to look to figure out the reason why it happens?

Thanks,
Nik

**Comment by rbrundritt** [comment]
Can you provide a lot more information? Which sample is this related to? 

If this is not one of the samples in this project, please use a standard support method for Azure Maps:

1. Forums: https://docs.microsoft.com/en-us/answers/topics/azure-maps.html
2. Azure Support: https://azure.microsoft.com/en-us/support/plans/

**Comment by cschotte** [comment]
you can add the `map.resize();` in the `ready` event to fix the problem, like:

```
map.events.add('ready', function () {
    map.resize();
}
```

**Comment by mitikov** [comment]
Wow, that fast :)

**Comment by mitikov** [comment]
@cschotte Thanks, it did the trick!

**Comment by mitikov** [comment]
Gents, are we willing to dive into diagnostics/tracing the bug, or can call it a day with by-hand resize solution?

**Comment by rbrundritt** [comment]
The root cause of your issue is most likely related to CSS. If the map div has no dimensions, the map won't be displayed. If the map div is initially hidden, then shown (div resized), you have to call the maps resize function as there is no event in browsers for when a div is resized (exception being if the browser window is resized and % dimensions are used).
