### ISSUE TITLE
[HowTo] Bring back old map styles

### ISSUE THREAD

**Issue by mitikov** [Azure-Samples/AzureMapsCodeSamples#112]
Hi folks, 

Azure Maps recently received fresh look: https://techcommunity.microsoft.com/t5/azure-maps-blog/there-is-a-new-style-of-maps-across-microsoft/ba-p/3788157

The UI change does not fit well with our project, and to be frank, it is quite a surprise to wake up with another map with zero changes on our side.

The 'updated' UI must had been released as new styles to avoid changes to existing.

I see folks on MS site reported this pain as well: https://learn.microsoft.com/en-us/answers/questions/1337105/is-there-any-way-to-revert-to-the-old-map-style?page=1&orderby=Helpful&comment=answer-1292376#newest-answer-comment

We've reached out our `MS success manager`, but it landed nowhere despite agreeing on behavior change out of blue.

Could you please provide a way to see old maps style?

Thanks.

**Comment by cschotte** [comment]
Thanks for your feedback and reaching out to our team.  As mentioned in our latest Tech community Blogpost, [here](https://techcommunity.microsoft.com/t5/azure-maps-blog/there-is-a-new-style-of-maps-across-microsoft/ba-p/3788157), we have implemented all new “Styles” to our Azure Maps rendering services. The decision to move forward with this new style was agreed with the objective of unifying all styles across all Microsoft Maps. Moreover, the changes were made explicit to the style and not UI or front-end API parameters, therefore, no break changes should have occurred. This process was chosen by design to have minimal-to-no impact to customers
