### ISSUE TITLE
Adding method to data source to allow string Geojson

### ISSUE THREAD

**Issue by jphines57** [Azure-Samples/AzureMapsCodeSamples#131]
The only method that is provided is to import from a URL in the JavaScript, which is almost never the case in the real world. Can you please add a new method or function that will allow a string of GeoJSON to be passed in to set the data source, please.

**Comment by rbrundritt** [comment]
There are actually a lot of samples that show this (roughly 105 of the samples based on a quick search). Also importing data via a URL is actually more common done as you could have this point to a REST service that queries your database. 

Usually, developers have their JSON data in the format of a JSON object rather than a string, usually as part of the import process. If you have a GeoJSON string, you have to first turn it into a JSON object, which you can do by using the JavaScript function `JSON.parse` (standard part of JavaScript). From there you can pass the object into the datasources `add` function. For example:

```javascript
var datasource = new atlas.source.DataSource();

//If you retrieved your data as a JSON object rather than as a string, you can either pass it into the datasources add function, or if the URL is returning only GeoJSON data, you could use the importDataFromUrl function.
var geojsonObj = JSON.parse('{"type":"Feature","geometry":{"type":"Point", "coordinates":[0,0]},"properties":{}}');

datasource.add(geojsonObj);
```

You will find most of the samples that add GeoJSON directly into a data source use the help methods in the `atlas.data` namespace which is a simple GeoJSON wrapper and just makes it easier to create GeoJSON objects in code.

**Comment by jphines57** [comment]
@rbrundritt I appreciate the examples, I'm try them tomorrow. So how do you add authorization headers to the datasource before calling importFromUrl() ?

**Comment by cschotte** [comment]
You can always fetch() data from an API using the the fetch() function in JavaScript, and add any headers you like.

**Comment by rbrundritt** [comment]
There are two methods for doing this. The first is to use fetch and have it return the result as JSON. Then you can simply use the `add` function for the datasource. Many use that approach as it's a standard way to call a REST service and gives you the most flexibility. It has all the options you could need, plus by being a native JavaScript feature, can be used on its own which is nice for different scenarios, or if you ever end up moving to another map control.

The second method is to use the `importFromUrl` function in combination with a lesser known option of the map itself called `transformRequest`. This is documented here: https://learn.microsoft.com/en-us/azure/azure-maps/map-create#request-transforms Here is a quick example of how this could be used in your scenario:

```javascript
var map = new atlas.Map('myMap', {
    transformRequest: function (url, resourceType) {
        //Check to see if the request is to the specified endpoint. Any kind of string match can be done as you see fit.
        if (url.indexOf('https://examples.com') > -1) {
            //Add custom headers to the request.
            return {
                url: url,
                header: {
                    //Add your custom headers, can be any headers your service/server supports.
                    username: 'myUsername',
                    password: 'myPassword'
                }
            };
        }

        //Return the URL unchanged by default.
        return { url: url };
    },

    //Other map options as needed.
});

//Later in your code when you want to load data do the following:

var datasource = new atlas.source.DataSource();
datasource.importFromUrl('https://examples.com/yourUrlRequest');
```

All that said, for JSON data I would use fetch with the datasources `add` function purely because that could be easily reused without the map which opens up more possibilities later (e.g. maybe you want to do some preprocessing in a web worker). The `transformRequest` option is useful for more complex scenarios, like when you need to add headers to map tile requests. It has a couple other interesting benefits:

- It intercepts all requests made by the map, so this could be used to redirect requests through a proxy if needed. The 
- If you are calling Azure Maps services within the map control, for example you add additional tile layer from Azure Maps Render service, you can replace `at with `https://{azMapsDomain}/` and under the hood the default behaviour of this transform sets the auth of the request to the same used by the map which can make things easy when using a more advanced auth option for Azure Maps. Also the domain for the request will be set to the same as the map (there is a gov cloud endpoint for Azure Maps, but this feature is less likely to be relevant to you). Here is a code sample that does this with vector traffic tiles from Azure Maps: https://samples.azuremaps.com/?sample=vector-tile-heat-map
