### ISSUE TITLE
Drawing Line Color?

### ISSUE THREAD

**Issue by JohnStraumann66** [Azure-Samples/AzureMapsCodeSamples#38]
Is it possible to add the ability to select the line color to the toolbar? So for example, I want to use lines to draw 4 or 5 shapes, can I change the line color for each shape?

> Ensure this is the right place
> ---------------------------------

Ensur this is the right place to report your issue.

- If your **issue is with the Azure Maps platform itself** and not specific to a code sample gallery, please conenct with the Azure support team at https://azure.com/support or report the issue on the forums: https://stackoverflow.com/questions/tagged/azure-maps 
- If your issue is with the **official Azure Maps documentation** you can use the feedback button on the documentation page to directly report the issue to the documentation team.

Reporting these types of issues using this methods will likely result in your issue being resolved quicker than if reported here.

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS, Browser and Version?
> Windows 7, 8 or 10. Android, iOS.
> Edge, Chrome, Firefox, Safari

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by rbrundritt** [comment]
Currently there is no color picker built in, and unfortunately due to a bug with events when in edit mode, its not easy to implement this yourself. I do have a workaround for the edit event bug (fix coming to production in about a month), however it doesn't work with lines, only polygons (can't seem to figure out the issue with lines currently). Note that the drawing tools module is in preview still.

Using the workaround or waiting for the fix you could do this by updating the line layer in the drawing manager so that it grabs the color from the properties of a shape. Then after a shape has being drawn, or is selected when in edit mode, you could change the color property of the shape. 

I took a crack at it, but there is no way to modify the preview style yet, so the experience isn't great. Here is the rough example I've put together so far: https://azuremapscodesamples.azurewebsites.net/Experimental/Simple%20drawing%20tools%20color%20picker.html

All that said, I took the approach of trying to tie this into the existing workflow (i.e. when in edit mode, get selected shape). Another approach that would likely work better currently would be to have a button to select which shape you want to change the color of, then select the shape on click. Then using style properties and data driven styling on the drawing layers would work. 

I'm planning to put together a sample with advanced drawing scenarios that will include things such as these, but it will likely be a few months before I have a chance to work on that.

**Comment by zahra-cell** [comment]
I have a series of points in the shapefile format. I need to have a polygon layer that shows the areas that have access to the points through 5 minutes walk. This is very similar to what we have here for a selected location. But, I need to run it for a group of points and be able to export the created polygons. Is it possible?

**Comment by rbrundritt** [comment]
@zahra-cell Please post this as a question in the forums: https://docs.microsoft.com/en-us/answers/topics/azure-maps.html
 
This question is unrelated to this issue.
