### ISSUE TITLE
What IDE/tool is used to develop the Azure Maps Code Samples?

### ISSUE THREAD

**Issue by sabuncu** [Azure-Samples/AzureMapsCodeSamples#41]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
> Information on IDE/tool used to develop the Azure Maps Code Samples provided in this repo.
> For example, how was the single page application interactiveSearch.html (under Tutorials) developed? 
> Is it possible to use Visual Studio 2019, and if so how?
> Is it possible to use VS Code, and if so, what extensions?

### OS, Browser and Version?
> Windows 10 2004
> Firefox

### Mention any other details that might be useful

Thank you.

**Comment by rbrundritt** [comment]
The full code sample site was created in Visual Studio 2019, but mainly because of the one click option to deploy to Azure. You don't need anything fancy to create HTML pages. In fact, open up notepad on your computer, copy in the source code to the interactiveSearch.html file and save the file with an "html" extension. Then double click on the file to open it in a browser and you will see that app running. 

Visual Studio code is a good option if you are looking for an IDE. If you are looking for something basic and don't need deployment and other automation tools, try out Notepad++. Its a great light weight editor that's fast. I use it all the time to manipulate data files.

**Comment by sabuncu** [comment]
Rick, thank you for your response.  I in fact have that sample running successfully, with my own subscription ID.

My question rather is *how* that HTML page was created.  You mention it was created using VS 2019.  What project type was used?

I see an AzureMapsCodeSamples.csproj file in the repo, but given that the sample is an HTML file, I am not sure that is the correct item.  I am well versed in VS and C#, but not in creating HTML/JS apps.  

Thank you again.  Regards.

**Comment by rbrundritt** [comment]
The code sample project is a VS2019 solution. I used the "ASP.NET Web Application" project template for the whole site. For html pages, they are simple flat files. Simply add ".html" to a file. I f you look through the file types when adding a new file, there should be a html file template which is really basic. Here is a video: https://www.youtube.com/watch?v=PgqqTXbseRM

**Comment by sabuncu** [comment]
OK, got it, thank you so much.  Regards.
