### ISSUE TITLE
Bug Report: Unable to drag and drop files on map

### ISSUE THREAD

**Issue by KanupriyaGoel** [Azure-Samples/AzureMapsCodeSamples#52]
I am trying to drap and drop shape files in an angular application.

I have used code as per the same.

Shapefile.js is installed using npm install and catiline.js is added directly in index.html.
In the component I have used.

Declare var catiline:any;
Rest all the code is used the same way. shpworker.data(e.target.result) returns a promise but it doesnt get resolved.

Please let me know if I need to share the code.

Browser: Chome
OS: Windows 10
Angular 8

**Comment by rbrundritt** [comment]
I suspect the issue is related to the content security policy (CSP) used in your angular app. Since this sample is using web workers, its possible that your CSP is blocking that and thus the promise is never responded to since the worker never initiates. 

I won't be able to provide much guidance on debugging the shapefile.js file. Try asking on that projects site: https://github.com/calvinmetcalf/shapefile-js

Also note that this approach to loading shapefile's is primarily meant for smaller files (<10MB).
