### ISSUE TITLE
Atlas-drawing module extensibility?

### ISSUE THREAD

**Issue by markphillips100** [Azure-Samples/AzureMapsCodeSamples#94]
Hoping someone on the SDK team can answer this one.

I've asked a few questions in regards to drawing functionality, both on stackoverflow and learn.microsoft.com.  The previous program manager (rbrundritt - thank you) has been kind enough to answer and informs me that the functions I require are not possible (without some hackery on my part) and not a priority for the team to extend the current library either.  I understand projects have priorities, resource limitations, etc.  However, my requirements don't go away with this knowledge.

I'm left with a quandary.  I must use Azure Maps as I must use the indoor map feature.  No other solution on the market supports what I need so I am committed to Azure Maps in that regard.  However, I also need slightly more enhanced drawing capability for polygons than is currently available.

I am looking for a user experience similar to what's available in MapBox drawing and extension modules when it comes to both drawing and editing a polygon.  Specifically the following:
1. A delete-vertex whilst in Edit Geometry mode. Mapbox drawing supports this with a vertex single click and click of trash icon.  This can be experienced at [geojson.io](https://geojson.io).  Also, the user should be able to cancel edits and have the original shape unchanged.
2. A snap-to-vertex when creating a new polygon and editing an existing one.  For clarity of what I am looking for, the behaviour as shown in the mapbox extension [mapbox-gl-draw-snap-mode](https://github.com/mhsattarian/mapbox-gl-draw-snap-mode) will show that this is different to what the atlas-drawing snap capability is, meaning this happens whilst editing.  
3. Ability to draw holes in existing polygons.  This isn't as much of a priority as the first 2 features but something that would be useful in some use cases.

So to my options. Assuming the team cannot supply the time or resource to extend functionality currently, can the following be answered please:
1. Are there plans on near horizon to make the drawing module open source, and if so how soon?  Not saying this solves my problem but I can at least make the changes I need in a fork.
2. If the answer to 1 is no, could this functionality be on the current SDK roadmap within the next 6 months?  6 months + implementation time possibly could still be something I can work to but only if it's a certainty.
4. If the answer to 2 is no, am I prohibited by any SDK licensing to writing my own equivalent of mapbox drawing that works with the underlying atlas.js, whether it be a new internal or OSS module?  A replacement for the current atlas-drawing.js essentially.  Not saying this is even pragmatic or possible but I need to rule out the licensing issue first.  I'd much rather be writing business functionality so this is not my preference by any stretch.  Just looking for a yes you can, or a no you cannot do that.
5. Any other options anyone can think of?

Thank you in advance.

**Comment by rbrundritt** [comment]
Most of these where a part of the original thinking for this feature as future extensions, but that never happened and not sure if or when they might bubble back up in priority (I'll try and get some clarity internally). That said, I have been considering creating an open-source module that adds these extended capabilities and adding it to the list of open source modules for the web SDK: https://github.com/microsoft/Maps/blob/master/AzureMaps.md#open-web-sdk-modules

I still have my original specification document, here is a brief list of additional features I had in mind. I have additional details for how most of these would function in my spec but there's a lot of internal info in that doc I can't share, so would have to do a cleanup before sharing it:

- Remove coordinates 
    -	On right click or long touch a drag handle displays a small popup that has a delete button in it. If the button is pressed, delete the coordinate. This popup should be hidden if the user mouse’s down or touches anything else on the page or exits the edit mode.
    -	User tabs to the drag handle via keyboard, then presses “-“, remove the coordinate. Alternatively, if it is easier, show the popup with the delete option so the user can easily tab into it.
- Edit Properties – A UI where additional metadata can be added to a shape. (This had mostly been built out, just not completed. Code is in the SDK today).
- Copy/Paste – make it easy to duplicate a shape. Possible resource https://learnosm.org/en/hot-tips/copy-paste/ 
- Draw/Edit – MultiPolygon, MultiPoint, MultiLinestring
- Cut holes – Provide the ability to draw a polygon on top of another polygon but it become a hole of that polygon. Support this for circle and rectangle, but those would output a polygon. For this and line splitting we will need a library that can perform Boolean operations, [this might be an option](https://github.com/voidqk/polybooljs) or [this](https://github.com/w8r/martinez)
- Cut/Split shape – If the shape is a linestring, polygon, circle or rectangle, let the user draw a linestring across it which will then be used to split the shape into two. Circle and possibly rectangle would be converted into a polygon because of this. 
- Magic wand – Let the user click a point on the map (possibly an image overlay they have added) and do a flood fill based on color (with tolerance) on all surrounding pixels to generate a polygon. (i.e. building floorplan overlaid on the map. User clicks inside a room and we generate a polygon of that room. Possible have artifact removal tolerance to remove text). 
- Orthogonalize Polygon –If the user draws a polygon it might not have perfectly square corners, this would straighten it out. OpenStreetMaps does this for in their drawing tools for building footprints. [Possible code1](https://github.com/openstreetmap/iD/blob/6ce2c5ea46b6bb89f8a3a3dd9d5794a920bbf610/modules/actions/orthogonalize.js), [possible code2](https://github.com/openstreetmap/potlatch2/blob/master/net/systemeD/potlatch2/tools/Quadrilateralise.as). Also investigate potential of supporting this for lines. 
- Merge/Union/Combine of Shapes – Possibly limit to like types (points, lines, or polygons but not a mix). Disconnected polygons would become MultiPolygons, but if the two polygons overlap, they would simply become a new single polygon. Have option to select by either clicking on individual shapes or by drawing polygon and getting all shapes within.
- Make Valid – Run some algorithms over a drawn shape to ensure that it is a valid spatial object (no kinks/overlapping edges/holes inside…) so that it can easily be imported into other spatial platforms, such as SQL server. 
- Measuring tools – Simply add measurement numbers to the drawing tools; lengths, radius, area. [This ended up being easy enough to achieve with the drawing tools as is, so not needed out of the box](https://samples.azuremaps.com/?sample=create-a-measuring-tool). But if we had an extension module that is loaded in addition to the drawing tools module, this might be a nice easy thing to add out of the box.

Some other ideas that were being considered but hadn't been scoped out:

- Undo/Redo – Nice to have but likely would add a lot of complexity. Use Z/R keyboard shortcuts like [ESRI](https://developers.arcgis.com/javascript/latest/api-reference/esri-views-2d-draw-Draw.html).
- Draw/Edit – ellipse, curve/spline
- Settings panel UI – There will be many options for the drawing tools such as rendering styles and snap grid size, in addition to being able to set these programmatically, also provide a UI where the user can modify these.
- Scale/Resize shape – with/without respecting aspect ratio
- Snap to geometries within the base map. We have road data, if the user wants to draw a polygon that has an edge that follows a road, can we make this easier to achieve. 
- Draw elevation – When we support extruded polygons we could support grabbing a polygon and stretching it vertically. Possibly offer 3D measuring tools like ESRI, however since we don’t have ground terrain this won’t be accurate, thus lower priority for the web control (Cesium might have a tool for this if customers need this scenario).
- Mirror shape – create a copy of it that is a mirror version.
- Geodesic Densifier – Add points between each set of coordinates that approximate a geodesic path.
- Buffer shape – Apply a distance buffer to a shape. This can already be achieved using Turf.js, but we could add a UI for setting this.
- Draw arrow – Create a polygon of an arrow and add to map. Rotate/drag already supported. 
- Flip shape – horizontal/vertical
- K-mean clustering of data points.
- 3D drawing – Sphere? 
- Styles – colors, patterns, icons – have as P3 as this is configured at the layer level, not the data level necessarily. 
- Bring forward/back – Similar to power point and would change order within the data source. However, this would be limited to be limited to shapes of the same type due to layering system. (i.e. you could move one point below another point, but not below a polygon, unless the layer the polygon is in is already above the point layer). 
- Box Select – When in this mode, disable box zoom and let the user use shift+click+drag to draw/select shapes on the map. 
- Fast Rectangle drawing option – Consider adding a rectangle drawing mode where the user draws two lines for faster drawing of rotated rectangles. Mouse down/drag for first line, on mouse up the second line should move with the mouse perpendicular to the first drawn line.  When the user clicks the mouse a second time. The rectangle is completed.

One important thing is that accessibility support has been a key focus of these drawing tools (and the Web SDK in general). The Azure Maps Web SDK is one of the most, if not the most, accessible map control currently available which is important for a lot of businesses.

**Comment by markphillips100** [comment]
@rbrundritt thank you for the most detailed response.  You are obviously very knowledgeable in this area.

I hope you have some luck with the team.  If not, I for one would love to see an open source extension with those capabilities.  And of course I understand the push to keep alignment with accessibility regardless of what implementation manifests.

Would you see this hypothetical extension incorporating or replacing atlas-drawing?  I ask due to the encapsulation in the current package kinda being what limits me from extending something myself.

As for the features you described, I like them all, but the Make Valid is something I would also make use of beyond my original short list.  Snap to vertex helps to create non-overlapping polygons but would be nice to select a set of polygons and adjust nearby vertices accordingly, or even just to highlight/style those that are overlapping.  Validating overlaps in a polygon layer would be really useful to me in a business context.

**Comment by rbrundritt** [comment]
Ideal it would extend the existing library, but I agree that unless a few bugs are fixed and a few small things aren't exposed, it would be hard to build something that can both extend and support all these scenarios. I'm still waiting to hear back from the Azure Maps team on their plans. Once we know, we can then come up with a plan of our own. Perhaps atlas.AdvancedDrawingTools will be a new community module.

**Comment by markphillips100** [comment]
@rbrundritt just checking any chance there's been some feedback from the team on this issue?

**Comment by markphillips100** [comment]
I think moving it open source would be best from my perspective, considering no published plan ahead for even the basic functionality I need pretty soon.

**Comment by markphillips100** [comment]
@rbrundritt is the SDK based/layered on maplibre by any chance, and would that also mean the underlying map instance is available?  If so I was wondering does that mean mapbox-gl-draw is something that could be consumed for drawing purposes?  I'm only thinking short term to get me past my immediate needs is all.

**Comment by rbrundritt** [comment]
Yes, Azure Maps uses MapLibre under the hood for rendering. The native map instance is access (not documented) but can be accessed using the path `map.map`, where the first `map` is your Azure Maps instance. In theory the mapbox-gl-draw library could be used, although there may be some issues since the mapbox namespace isn't exposed in Azure Maps, so if this library tries to access some class, it might throw an error.

**Comment by markphillips100** [comment]
Thanks for that. I understand why some things may not work. Would have to trial and see.
